spring:
  jpa:
    database: h2  # database? h2? ??
    open-in-view: false
    show-sql: true  # sql? log?? ???
    hibernate: # jpa entity? ??????? ?? ?????
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        # default_batch_fetch_size: 10
  datasource:
    url: jdbc:h2:mem:portfolio  # database url
    username: sa  # database username
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console # ?? ??